### ISSUE TITLE
simple_cut does not like a pathlib.Path object

### ISSUE THREAD

**Issue by gyger** [timetag/ETA#47]
It seems simple_cut does not like a path from pathlib. I run the following command.
`cut=eta.simple_cut(Path(file), 4)` and get the following error.

```
ERROR:__main__:encoding or errors without a string argument
Traceback (most recent call last):
  File "eta_runtime.py", line 141, in process_eta
  File "<string>", line 11, in <module>
  File "eta_runtime.py", line 227, in simple_cut
TypeError: encoding or errors without a string argument
```

**Comment by linzuzeng** [comment]
Fixed in ETA RC 5.6
